/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 31 déc. 2015, 14:38:51
 */
package typeFaster.frames;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author M_Zahi
 */
public class MainFrame extends javax.swing.JFrame {

    private static String lang = "AR";
    private static final String[] trans_ar = {"TypeFaster", "إختبر سرعتك في الكتابة على لوحة المفاتيح وذلك من خلال  لعبة مسلية تحتوي على كلمات بالعربية والفرنسية والإنجليزية.", "إلعب الآن"};
    private static final String[] trans_fr = {"TypeFaster", "Testez votre vitesse en tapant sur ​​le clavier avec un jeu divertissant contient des mots en arabe , français et anglais .", "Jouer"};
    private static final String[] trans_en = {"TypeFaster", "Test your speed in typing on the keyboard with an entertaining game contains words in Arabic, French and English.", "Play"};

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Button = new javax.swing.JButton();
        TextArea = new javax.swing.JTextArea();
        b_Arabe_lang = new javax.swing.JButton();
        b_English_lang = new javax.swing.JButton();
        b_franscais_lang = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        checkArabic = new javax.swing.JCheckBoxMenuItem();
        checkFrench = new javax.swing.JCheckBoxMenuItem();
        checkEnglish = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(-1,true));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(-1,true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("SansSerif", 1, 24));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("إختـبر سـرعتـك");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 310, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trainer-hands-colored.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Webp.net-resizeimage.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 290, 210));

        Button.setFont(new java.awt.Font("Tahoma", 1, 14));
        Button.setText("إلعب الآن");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 324, 139, 43));

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Serif", 0, 18));
        TextArea.setForeground(new java.awt.Color(-65024,true));
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        TextArea.setText("إختبر سرعتك في الكتابة على لوحة المفاتيح وذلك من خلال  لعبة مسلية تحتوي على كلمات بالعربية والفرنسية والإنجليزية");
        TextArea.setWrapStyleWord(true);
        TextArea.setBorder(null);
        TextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(TextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, 90));

        b_Arabe_lang.setBackground(new java.awt.Color(-65536,true));
        b_Arabe_lang.setForeground(new java.awt.Color(-65536,true));
        b_Arabe_lang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dz.png"))); // NOI18N
        b_Arabe_lang.setToolTipText("Arabic");
        b_Arabe_lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Arabe_langActionPerformed(evt);
            }
        });
        jPanel1.add(b_Arabe_lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 32, 24, -1));

        b_English_lang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/us.png"))); // NOI18N
        b_English_lang.setToolTipText("English");
        b_English_lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_English_langActionPerformed(evt);
            }
        });
        jPanel1.add(b_English_lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 32, 24, -1));

        b_franscais_lang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fr.png"))); // NOI18N
        b_franscais_lang.setToolTipText("French");
        b_franscais_lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_franscais_langActionPerformed(evt);
            }
        });
        jPanel1.add(b_franscais_lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 32, 25, -1));

        username.setFont(new java.awt.Font("Dialog", 1, 14));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setToolTipText("username");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 324, 121, 43));

        jMenu1.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("close");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("options");

        jMenu4.setText("language");

        checkArabic.setSelected(true);
        checkArabic.setText("العربية");
        checkArabic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkArabicActionPerformed(evt);
            }
        });
        jMenu4.add(checkArabic);

        checkFrench.setText("Français");
        checkFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFrenchActionPerformed(evt);
            }
        });
        jMenu4.add(checkFrench);

        checkEnglish.setText("English");
        checkEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEnglishActionPerformed(evt);
            }
        });
        jMenu4.add(checkEnglish);

        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
// TODO add your handling code here:
    if (!"".equals(username.getText())) {
        SecondFrame frame = new SecondFrame(lang, username.getText());
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Choose a username PLZ", "information", JOptionPane.INFORMATION_MESSAGE);
    }
}//GEN-LAST:event_ButtonActionPerformed

private void b_Arabe_langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Arabe_langActionPerformed
    lang = "AR";
    b_Arabe_lang.setBackground(Color.red);
    b_franscais_lang.setBackground(null);
    b_English_lang.setBackground(null);
    title.setText(trans_ar[0]);
    TextArea.setText(trans_ar[1]);
    Button.setText(trans_ar[2]);
    ////
    checkArabic.setSelected(true);
    checkFrench.setSelected(false);
    checkEnglish.setSelected(false);

}//GEN-LAST:event_b_Arabe_langActionPerformed

private void b_English_langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_English_langActionPerformed
    lang = "EN";
    b_Arabe_lang.setBackground(null);
    b_franscais_lang.setBackground(null);
    b_English_lang.setBackground(Color.red);
    title.setText(trans_en[0]);
    TextArea.setText(trans_en[1]);
    Button.setText(trans_en[2]);
    ////
    checkArabic.setSelected(false);
    checkFrench.setSelected(false);
    checkEnglish.setSelected(true);
}//GEN-LAST:event_b_English_langActionPerformed

private void b_franscais_langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_franscais_langActionPerformed
    lang = "FR";
    b_Arabe_lang.setBackground(null);
    b_franscais_lang.setBackground(Color.red);
    b_English_lang.setBackground(null);
    title.setText(trans_fr[0]);
    TextArea.setText(trans_fr[1]);
    Button.setText(trans_fr[2]);
    ///
    checkArabic.setSelected(false);
    checkFrench.setSelected(true);
    checkEnglish.setSelected(false);
}//GEN-LAST:event_b_franscais_langActionPerformed

private void checkArabicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkArabicActionPerformed
    checkArabic.setSelected(true);
    lang = "AR";
    checkFrench.setSelected(false);
    checkEnglish.setSelected(false);
    title.setText(trans_ar[0]);
    TextArea.setText(trans_ar[1]);
    Button.setText(trans_ar[2]);
    ///
    b_Arabe_lang.setBackground(Color.red);
    b_franscais_lang.setBackground(null);
    b_English_lang.setBackground(null);
}//GEN-LAST:event_checkArabicActionPerformed

private void checkFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFrenchActionPerformed
    checkArabic.setSelected(false);
    lang = "FR";
    checkFrench.setSelected(true);
    checkEnglish.setSelected(false);
    title.setText(trans_fr[0]);
    TextArea.setText(trans_fr[1]);
    Button.setText(trans_fr[2]);
    ///
    b_Arabe_lang.setBackground(null);
    b_franscais_lang.setBackground(Color.red);
    b_English_lang.setBackground(null);
}//GEN-LAST:event_checkFrenchActionPerformed

private void checkEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEnglishActionPerformed
    checkArabic.setSelected(false);
    lang = "EN";
    checkFrench.setSelected(false);
    checkEnglish.setSelected(true);
    title.setText(trans_en[0]);
    TextArea.setText(trans_en[1]);
    Button.setText(trans_en[2]);
    ///
    b_Arabe_lang.setBackground(null);
    b_franscais_lang.setBackground(null);
    b_English_lang.setBackground(Color.red);
}//GEN-LAST:event_checkEnglishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame frame = new MainFrame();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton b_Arabe_lang;
    private javax.swing.JButton b_English_lang;
    private javax.swing.JButton b_franscais_lang;
    private javax.swing.JCheckBoxMenuItem checkArabic;
    private javax.swing.JCheckBoxMenuItem checkEnglish;
    private javax.swing.JCheckBoxMenuItem checkFrench;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
